services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: agorapulse
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agorapulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db-test:
    image: postgres:latest
    container_name: postgres_db_test
    environment:
      POSTGRES_USER: agorapulse
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agorapulse
    ports:
      - "5432:5432"

volumes:
  postgres_data:
